-- ════════════════════════════════════════════════════
-- TODOS LOS PAÍSES DEL MUNDO (español)
-- Fuente: REST Countries API
-- ON CONFLICT evita duplicados con los ya insertados
-- ════════════════════════════════════════════════════

INSERT INTO tutti_frutti_words (category, letter, word) VALUES
-- A
('pais', 'A', 'Afganistán'),
('pais', 'A', 'Albania'),
('pais', 'A', 'Alemania'),
('pais', 'A', 'Andorra'),
('pais', 'A', 'Angola'),
('pais', 'A', 'Antigua y Barbuda'),
('pais', 'A', 'Arabia Saudí'),
('pais', 'A', 'Argelia'),
('pais', 'A', 'Argentina'),
('pais', 'A', 'Armenia'),
('pais', 'A', 'Australia'),
('pais', 'A', 'Austria'),
('pais', 'A', 'Azerbaiyán'),
-- B
('pais', 'B', 'Bahamas'),
('pais', 'B', 'Bangladés'),
('pais', 'B', 'Barbados'),
('pais', 'B', 'Baréin'),
('pais', 'B', 'Bélgica'),
('pais', 'B', 'Belice'),
('pais', 'B', 'Benín'),
('pais', 'B', 'Bielorrusia'),
('pais', 'B', 'Bolivia'),
('pais', 'B', 'Bosnia y Herzegovina'),
('pais', 'B', 'Botsuana'),
('pais', 'B', 'Brasil'),
('pais', 'B', 'Brunéi'),
('pais', 'B', 'Bulgaria'),
('pais', 'B', 'Burkina Faso'),
('pais', 'B', 'Burundi'),
('pais', 'B', 'Bután'),
-- C
('pais', 'C', 'Cabo Verde'),
('pais', 'C', 'Camboya'),
('pais', 'C', 'Camerún'),
('pais', 'C', 'Canadá'),
('pais', 'C', 'Chad'),
('pais', 'C', 'Chile'),
('pais', 'C', 'China'),
('pais', 'C', 'Chipre'),
('pais', 'C', 'Colombia'),
('pais', 'C', 'Comoras'),
('pais', 'C', 'Congo'),
('pais', 'C', 'Corea del Norte'),
('pais', 'C', 'Corea del Sur'),
('pais', 'C', 'Costa de Marfil'),
('pais', 'C', 'Costa Rica'),
('pais', 'C', 'Croacia'),
('pais', 'C', 'Cuba'),
-- D
('pais', 'D', 'Dinamarca'),
('pais', 'D', 'Dominica'),
-- E
('pais', 'E', 'Ecuador'),
('pais', 'E', 'Egipto'),
('pais', 'E', 'El Salvador'),
('pais', 'E', 'Emiratos Árabes Unidos'),
('pais', 'E', 'Eritrea'),
('pais', 'E', 'Eslovaquia'),
('pais', 'E', 'Eslovenia'),
('pais', 'E', 'España'),
('pais', 'E', 'Estados Unidos'),
('pais', 'E', 'Estonia'),
('pais', 'E', 'Etiopía'),
-- F
('pais', 'F', 'Filipinas'),
('pais', 'F', 'Finlandia'),
('pais', 'F', 'Fiyi'),
('pais', 'F', 'Francia'),
-- G
('pais', 'G', 'Gabón'),
('pais', 'G', 'Gambia'),
('pais', 'G', 'Georgia'),
('pais', 'G', 'Ghana'),
('pais', 'G', 'Granada'),
('pais', 'G', 'Grecia'),
('pais', 'G', 'Guatemala'),
('pais', 'G', 'Guinea'),
('pais', 'G', 'Guinea Ecuatorial'),
('pais', 'G', 'Guinea-Bisáu'),
('pais', 'G', 'Guyana'),
-- H
('pais', 'H', 'Haití'),
('pais', 'H', 'Honduras'),
('pais', 'H', 'Hungría'),
-- I
('pais', 'I', 'India'),
('pais', 'I', 'Indonesia'),
('pais', 'I', 'Irak'),
('pais', 'I', 'Irán'),
('pais', 'I', 'Irlanda'),
('pais', 'I', 'Islandia'),
('pais', 'I', 'Israel'),
('pais', 'I', 'Italia'),
-- J
('pais', 'J', 'Jamaica'),
('pais', 'J', 'Japón'),
('pais', 'J', 'Jordania'),
-- K
('pais', 'K', 'Kazajistán'),
('pais', 'K', 'Kenia'),
('pais', 'K', 'Kirguistán'),
('pais', 'K', 'Kiribati'),
('pais', 'K', 'Kuwait'),
-- L
('pais', 'L', 'Laos'),
('pais', 'L', 'Lesoto'),
('pais', 'L', 'Letonia'),
('pais', 'L', 'Líbano'),
('pais', 'L', 'Liberia'),
('pais', 'L', 'Libia'),
('pais', 'L', 'Liechtenstein'),
('pais', 'L', 'Lituania'),
('pais', 'L', 'Luxemburgo'),
-- M
('pais', 'M', 'Madagascar'),
('pais', 'M', 'Malasia'),
('pais', 'M', 'Malaui'),
('pais', 'M', 'Maldivas'),
('pais', 'M', 'Mali'),
('pais', 'M', 'Malta'),
('pais', 'M', 'Marruecos'),
('pais', 'M', 'Mauricio'),
('pais', 'M', 'Mauritania'),
('pais', 'M', 'México'),
('pais', 'M', 'Micronesia'),
('pais', 'M', 'Moldavia'),
('pais', 'M', 'Mónaco'),
('pais', 'M', 'Mongolia'),
('pais', 'M', 'Montenegro'),
('pais', 'M', 'Mozambique'),
('pais', 'M', 'Myanmar'),
-- N
('pais', 'N', 'Namibia'),
('pais', 'N', 'Nauru'),
('pais', 'N', 'Nepal'),
('pais', 'N', 'Nicaragua'),
('pais', 'N', 'Níger'),
('pais', 'N', 'Nigeria'),
('pais', 'N', 'Noruega'),
('pais', 'N', 'Nueva Zelanda'),
-- O
('pais', 'O', 'Omán'),
-- P
('pais', 'P', 'Países Bajos'),
('pais', 'P', 'Pakistán'),
('pais', 'P', 'Palaos'),
('pais', 'P', 'Panamá'),
('pais', 'P', 'Papúa Nueva Guinea'),
('pais', 'P', 'Paraguay'),
('pais', 'P', 'Perú'),
('pais', 'P', 'Polonia'),
('pais', 'P', 'Portugal'),
-- R
('pais', 'R', 'Reino Unido'),
('pais', 'R', 'República Centroafricana'),
('pais', 'R', 'República Checa'),
('pais', 'R', 'República Dominicana'),
('pais', 'R', 'Ruanda'),
('pais', 'R', 'Rumania'),
('pais', 'R', 'Rusia'),
-- S
('pais', 'S', 'Samoa'),
('pais', 'S', 'San Cristóbal y Nieves'),
('pais', 'S', 'San Marino'),
('pais', 'S', 'San Vicente y las Granadinas'),
('pais', 'S', 'Santa Lucía'),
('pais', 'S', 'Santo Tomé y Príncipe'),
('pais', 'S', 'Senegal'),
('pais', 'S', 'Serbia'),
('pais', 'S', 'Seychelles'),
('pais', 'S', 'Sierra Leona'),
('pais', 'S', 'Singapur'),
('pais', 'S', 'Siria'),
('pais', 'S', 'Somalia'),
('pais', 'S', 'Sri Lanka'),
('pais', 'S', 'Sudáfrica'),
('pais', 'S', 'Sudán'),
('pais', 'S', 'Sudán del Sur'),
('pais', 'S', 'Suecia'),
('pais', 'S', 'Suiza'),
('pais', 'S', 'Surinam'),
-- T
('pais', 'T', 'Tailandia'),
('pais', 'T', 'Taiwán'),
('pais', 'T', 'Tanzania'),
('pais', 'T', 'Tayikistán'),
('pais', 'T', 'Timor Oriental'),
('pais', 'T', 'Togo'),
('pais', 'T', 'Tonga'),
('pais', 'T', 'Trinidad y Tobago'),
('pais', 'T', 'Túnez'),
('pais', 'T', 'Turkmenistán'),
('pais', 'T', 'Turquía'),
('pais', 'T', 'Tuvalu'),
-- U
('pais', 'U', 'Ucrania'),
('pais', 'U', 'Uganda'),
('pais', 'U', 'Uruguay'),
('pais', 'U', 'Uzbekistán'),
-- V
('pais', 'V', 'Vanuatu'),
('pais', 'V', 'Venezuela'),
('pais', 'V', 'Vietnam'),
-- Y  (no está en AVAILABLE_LETTERS pero se incluye por completitud)
('pais', 'Y', 'Yemen'),
-- Z
('pais', 'Z', 'Zambia'),
('pais', 'Z', 'Zimbabue')
ON CONFLICT (category, word) DO NOTHING;
